### ISSUE TITLE
DEAR GOD WHAT HAVE I CREATED

### ISSUE THREAD

**Issue by Bismarckingit** [DoktorKure/Vic-II-Modern-History-Mod-MHM#5]
here is...this hellish abomination of a file, pls look over
[Free Hungary.txt](https://github.com/DoktorKure/Vic-II-Modern-History-Mod-MHM/files/9204173/Free.Hungary.txt)

**Comment by DoktorKure** [comment]
Reviewed, the event structure looks good, I reupload the file here and changed the formatting by adding spacing between event functions. I find it's better this way as it's easier on the eyes.
[Free_Hungary.txt](https://github.com/DoktorKure/Vic-II-Modern-History-Mod-MHM/files/9204842/Free_Hungary.txt)
